---

- name: check if newer install
  stat:
    path: ~/.ansible_devtools
  register: new_install

- name: Sync local theme folder to remote
  synchronize:
    src: assets/elementary-osx-theme/Themes/
    dest: /usr/share/themes/
    compress: no
    times: no
  become: yes

- name: Sync local icons folder to remote
  synchronize:
    src: assets/elementary-osx-theme/Icons/
    dest: /usr/share/icons/
    compress: no
    times: no
  become: yes

- name: Sync local plank folder to remote
  synchronize:
    src: assets/elementary-osx-theme/Plank/
    dest: ~/.local/share/plank/themes/
    compress: no
    times: no

- name: Sync wallpaper folder to remote
  synchronize:
    src: assets/elementary-osx-theme/sierra.jpg
    dest: ~/.local/share/backgrounds/
    compress: no
    times: no

- name: Apply osx theme
  shell: >
    export DISPLAY=:0.0;
    gsettings set org.pantheon.desktop.gala.appearance button-layout close,minimize,maximize;
    gsettings set org.gnome.desktop.interface gtk-theme 'Light-Mode';
    gsettings set org.gnome.desktop.interface icon-theme 'Light-Mode';
    gsettings set org.gnome.desktop.interface cursor-theme 'Light-Mode';
    gsettings set org.gnome.desktop.wm.preferences theme 'Light-Mode';
    gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <'close,minimize,maximize:menu'>, 'Gtk/DialogsUseHeader': <0>, 'Gtk/ShellShowsAppMenu': <0>}";
    gsettings set org.gnome.desktop.wm.preferences button-layout close,minimize,maximize;
    gsettings set org.gnome.desktop.background picture-uri ~/.local/share/backgrounds/sierra.jpg;
    gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DialogsUseHeader': <0>, 'Gtk/ShellShowsAppMenu': <0>, 'Gtk/DecorationLayout': <'close:menu,maximize'>}"
  args:
    executable: /bin/bash
