---

- name: elementary-tweaks repositoy
  apt_repository:
    repo: ppa:philip.scott/elementary-tweaks 
    #'deb http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic main'
  become: yes

- name: Install packages
  apt: name={{ item }} state=installed update_cache=true force=yes
  with_items: "{{ devtools_packages }}"
  become: yes
