---

- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - role: oh-my-zsh
      tags: ['install']
    - role: base
      tags: ['install']
    - role: vim
      tags: ['devtool']
    - role: devtools
      tags: ['devtool', 'osx']
    - role: git
      become: yes
      tags: ['devtool', 'git']
    - role: gitconfig
      tags: ['devtool', 'git']
    - role: repos
      tags: ['devtool', 'git']
    - role: fonts
      tags: ['webtool']
    - role: chrome
      become: yes
      tags: ['webtool']
    - role: atom
      tags: ['devtool']
    - role: sublimetext
      become: yes
      tags: ['devtool']
    - role: FGtatsuro.python-requirements
      tags: ['install']
    - role: FGtatsuro.virtualbox
      tags: ['vagrant', 'virtualization']
    - role: libvirtd
      become: yes
      tags: ['vagrant', 'virtualization']
    - role: vagrant
      tags: ['vagrant', 'virtualization']
    - role: docker
      become: yes
      tags: ['virtualization']
    - role: vagrantup
      tags: ['vagrant']

  pre_tasks:
    - name: Wait for App Center (sigh...)
      shell: >
        while fuser /var/lib/apt/lists/lock; do sleep 1; done;
        while fuser /var/cache/apt/archives/lock; do sleep 1; done;
        while fuser /var/lib/dpkg/lock; do sleep 1; done;
      become: true
      args:
        executable: /bin/bash

  tasks:
    - name: Disable Guest account
      shell: echo "[SeatDefaults]\nallow-guest=false\n" > /etc/lightdm/lightdm.conf.d/50-no-guest.conf
      become: true
